#!/bin/bash
# scaffold.sh — Create complete 6-layer memory directory structure
# Usage: ./scaffold.sh [workspace_root] [templates_dir]

WORKSPACE="${1:-.}"
TEMPLATES="${2:-./templates}"
TIMESTAMP=$(date -Iseconds)

echo "=== FORGE GENESIS: Scaffold ==="
echo "Workspace: $WORKSPACE"
echo "Templates: $TEMPLATES"
echo "Time: $TIMESTAMP"

# Pre-flight: check for existing memory
if [ -f "$WORKSPACE/MEMORY.md" ] || [ -d "$WORKSPACE/memory" ] || [ -d "$WORKSPACE/life" ]; then
  echo "ERROR: Existing memory artifacts detected. Use FORGE RECALL instead."
  exit 1
fi

# Create directories
DIRS=(
  "memory/logs"
  "memory/wiki"
  "memory/connections"
  "memory/recall"
  "life/projects"
  "life/areas"
  "life/resources"
  "life/archive"
  "scripts"
  ".forge/genesis"
)

for dir in "${DIRS[@]}"; do
  mkdir -p "$WORKSPACE/$dir"
  echo "Created: $dir"
done

# Copy templates
if [ -d "$TEMPLATES" ]; then
  for tmpl in MEMORY.md AGENTS.md PARA.md daily-note.md concept.md HOTCACHE.md WORKSPACE_MEMORY.md; do
    if [ -f "$TEMPLATES/$tmpl" ]; then
      case "$tmpl" in
        MEMORY.md)     cp "$TEMPLATES/$tmpl" "$WORKSPACE/MEMORY.md" ;;
        AGENTS.md)     cp "$TEMPLATES/$tmpl" "$WORKSPACE/AGENTS.md" ;;
        PARA.md)       cp "$TEMPLATES/$tmpl" "$WORKSPACE/life/README.md" ;;
        HOTCACHE.md)   cp "$TEMPLATES/$tmpl" "$WORKSPACE/memory/recall/HOTCACHE.md" ;;
        daily-note.md) cp "$TEMPLATES/$tmpl" "$WORKSPACE/memory/logs/.template.md" ;;
        concept.md)    cp "$TEMPLATES/$tmpl" "$WORKSPACE/memory/wiki/.template.md" ;;
        *)             cp "$TEMPLATES/$tmpl" "$WORKSPACE/.forge/genesis/$tmpl" ;;
      esac
      echo "Copied: $tmpl"
    fi
  done
fi

# Create initial wiki index
cat > "$WORKSPACE/memory/wiki/index.md" << 'EOF'
# Knowledge Index
# Auto-generated by FORGE GENESIS
# Concepts: 0 | Compiled: never

<!-- No concepts yet — run compilation after your first session -->
EOF

# Install log
cat > "$WORKSPACE/.forge/genesis/install-log.md" << EOF
# FORGE GENESIS Install Log
- Installed: $TIMESTAMP
- Runtime: \${FORGE_RUNTIME:-unknown}
- Directories created: ${#DIRS[@]}
- Templates copied: $(ls "$TEMPLATES" 2>/dev/null | wc -l)
EOF

echo "=== SCAFFOLD COMPLETE ==="
echo "Directories: ${#DIRS[@]}"
echo "Next: Run wire-hooks.sh to install capture hooks"
